import express from 'express';
import cors from 'cors';
import register from './routes/register.route.js';
import login from './routes/login.route.js';
import profile from './routes/profile.route.js';
const app = express();
app.use(express.json());
app.use(cors());
app.use('/api/auth/',register);
app.use('/api/auth/',login);
app.use('/api/',profile);
export default app;